### ISSUE TITLE
invalid geometry in districts geojson

### ISSUE THREAD

**Issue by shubhamdutta26** [datta07/INDIAN-SHAPEFILES#10]
Hello, I am trying to import your awesome maps of India into R using the sf package. When computing centroids for the districts its giving me an error:
`Loop 74 is not valid: Edge 1639 crosses edge 1650`
It seems that the error is occuring here in the district of North  & Middle Andaman:
`
  dtname                  stname       stcode11 dtcode11 year_stat SHAPE_Length SHAPE_Area OBJECTID test  Dist_LGD State_LGD                  geometry
  <chr>                   <chr>        <chr>    <chr>    <chr>            <dbl>      <dbl>    <int> <chr>    <int>     <int>        <MULTIPOLYGON [°]>
1 North  & Middle Andaman ANDAMAN & N… 35       639      2011_c        3176701.     3.65e9      263 NA         632        35 (((92.78642 12.07485, 92…`

**Comment by datta07** [comment]
can you elaborate from which district file (is it Indian districts file or A&N district file) you are getting this error you are getting this error?

**Comment by shubhamdutta26** [comment]
It is happening in the INDIA_DISTRICTS.geojson file.

**Comment by Kaviarasan-G** [comment]
Hi sir,
I have working with this Geojso file for my project while working I found out some issue in the file TAMILNADU_SUBDISTRICTS_topojson

The Issue is currently tamil nadu new added some districts and block also updated, can You please update the current districts and sub districts in the file.

**Comment by datta07** [comment]
> It is happening in the INDIA_DISTRICTS.geojson file.

can you try simplifying this using the mapshaper.org

**Comment by datta07** [comment]
> Hi sir, I have working with this Geojso file for my project while working I found out some issue in the file TAMILNADU_SUBDISTRICTS_topojson
> 
> The Issue is currently tamil nadu new added some districts and block also updated, can You please update the current districts and sub districts in the file.

@Kaviarasan-G can you specify the examples of recently added blocks or districts missing

**Comment by Kaviarasan-G** [comment]
> > Hi sir, I have working with this Geojso file for my project while working I found out some issue in the file TAMILNADU_SUBDISTRICTS_topojson
> > The Issue is currently tamil nadu new added some districts and block also updated, can You please update the current districts and sub districts in the file.
> 
> @Kaviarasan-G can you specify the examples of recently added blocks or districts missing

Thanks for this Reply.
List of New Districts: Tenkasi, Tirupattur, Kallakurichi, Ranipet, Chengalpet, and Mayiladudhurai.
Sub Districts of New Districts: https://www.cra.tn.gov.in/tn_taluks.pdf  available in this link sir.

**Comment by Kaviarasan-G** [comment]
@akuladatta bro, any update on the new district issue.

**Comment by datta07** [comment]
@Kaviarasan-G The Tamil Nadu district file is already updated, can you check again in TAMIL NADU folder. it has 38 districts
