### ISSUE TITLE
What is the source of this data?

### ISSUE THREAD

**Issue by rbhatia46** [datta07/INDIAN-SHAPEFILES#3]
Interesting collation of data, thanks for open sourcing the same, can you please talk about the source of this data, just wanted to understand how accurate these boundaries are ?

Thanks

**Comment by datta07** [comment]
Collected shapes from various online sources and added values with some automated programs.

**Comment by stepps00** [comment]
Thanks for this data effort, @datta07 - great to see new districts. I'm interested in using this data for an open source project, but have a question - was any of this data pulled from OpenStreetMap? Would be great if you have any more detail about the original sources, even if it's not OSM-sourced. Thanks!
