### ISSUE TITLE
2 features need to be merged in Andhra shapefile

### ISSUE THREAD

**Issue by shijithpk** [datta07/INDIAN-SHAPEFILES#6]
Hi Akula, thanks for all the work you've put in to creating and sharing all these files.

Just wanted to let you know of a small correction. This is in the file for [assembly seats](https://github.com/datta07/INDIAN-SHAPEFILES/blob/master/STATES/ANDHRA%20PRADESH/ANDHRA%20PRADESH_ASSEMBLY.geojson) in Andhra Pradesh.

So the assembly seat Bhadrachalam (ST) is actually merged with RAMPACHODAVARAM now. Rest all seems fine. Just thought i'd let you know. Again, thank you for all the hard work :)

**Comment by krishna232** [comment]
Hi Akula,
@shijithpk Shijith Kunhitty,
@datta07 
Thanks a lot for the maps. need your help for merging Bhadrachalam (ST) is actually merged with RAMPACHODAVARAM.

can you please guide me how it can be done. 

thanks again  for all the hard work

**Comment by datta07** [comment]
Hi @shijithpk @krishna232 

Thanks for pointing this. had fixed this in latest commit :

file link : https://github.com/datta07/INDIAN-SHAPEFILES/blob/master/STATES/ANDHRA%20PRADESH/ANDHRA%20PRADESH_ASSEMBLY.geojson

also check analysis on the latest election result of AP : https://garudadevdataservices.github.io/map/?map=ap2024asm
